# -*- coding: utf-8 -*-
"""MongoDR_Qdrant_V1_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10qrnEjlRJNaSmH58CdhZqKXyNG8PSnoi
"""

!pip install pymongo

!pip install qdrant-client

!pip install python-dotenv

from dotenv import load_dotenv
from pymongo import MongoClient
from qdrant_client import QdrantClient
import os

# Carrega variáveis do .env
load_dotenv(dotenv_path=".env")  # Certifique-se que o caminho está correto

# MongoDB
mongo_uri = os.getenv("MONGO_URI")
print("✅ URI Mongo:", mongo_uri)  # Diagnóstico

if not mongo_uri:
    raise ValueError("❌ Variável MONGO_URI não carregada. Verifique o .env.")

client = MongoClient(mongo_uri)
db = client["vibe_learning"]

# Qdrant
qdrant_url = os.getenv("QDRANT_URL")
qdrant_api_key = os.getenv("QDRANT_API_KEY")

if not qdrant_url or not qdrant_api_key:
    raise ValueError("❌ Variáveis Qdrant não carregadas. Verifique o .env.")

qdrant_client = QdrantClient(
    url=qdrant_url,
    api_key=qdrant_api_key
)

# Testes de diagnóstico
print("🧪 Coleções MongoDB:", client.list_database_names())
print("🧪 Coleções Qdrant:", qdrant_client.get_collections())

with open(".env", "r", encoding="utf-8") as f:
    print("📄 Conteúdo do .env:\n", f.read())

from dotenv import load_dotenv
import os

load_dotenv(dotenv_path=".env")

mongo_uri = os.getenv("MONGO_URI") or "mongodb+srv://..."
qdrant_url = os.getenv("QDRANT_URL") or "https://..."
qdrant_api_key = os.getenv("QDRANT_API_KEY") or "ey..."

print("URI Mongo:", mongo_uri)

with open(".env", "w", encoding="utf-8") as f:
    f.write("""\
MONGO_URI=mongodb+srv://mattediVibe:Vibe1234@vibe-learning.vndvwiu.mongodb.net/?retryWrites=true&w=majority
QDRANT_URL=https://41868fdd-8c13-41d5-8a16-f16c2bd3c00a.us-east4-0.gcp.cloud.qdrant.io:6333
QDRANT_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.INiYWf8icoZ8BxQchwSsKjgq2APidjTox_orSzsRrho
""")

print("✅ Arquivo .env criado com sucesso.")

from dotenv import load_dotenv
import os

load_dotenv(".env")

print("Mongo URI:", os.getenv("MONGO_URI"))
print("Qdrant URI:", os.getenv("QDRANT_URL"))

!git config --global user.email "mattediblu@gmail.com"
!git config --global user.name "Mattedi"